### ISSUE TITLE
Build a workflow for integrating example IDC data against standardized vocabularies; 2 imaging MVP data sets to test CEDAR/other tools for data annotation

### ISSUE THREAD

**Issue by llchristopherson** [cancerDHC/tools#17] opened 2020-09-29 15:08 UTC
From Resham's https://docs.google.com/document/d/147oFEWeOzcUTkL6jFqd93Q6uO91D8Gvjpd-RGVMQ1LE/edit

**Comment by gaurav** [comment] 2020-09-29 15:30
I think this is a duplicate of #4?

**Comment by balhoff** [comment] 2020-10-02 17:15
Agree, I will close.

**Closed as completed by balhoff** 2020-10-02 17:15 UTC
Labels: discussion needed
